name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Angular App
      run: |
        cd ClientApp
        npm install
        npm run build -- 

    - name: Build .NET App
      run: |
        dotnet restore
        dotnet build
        dotnet publish --configuration Release --output ./build

    - name: Deploy
      # Use the appropriate action for your chosen hosting service
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: master # The branch the action should deploy to.
        folder: ClientApp/dist # The folder the action should deploy.